#Github login

#Google login

logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost/poster
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
