spring:
  datasource:
    url: jdbc:mysql://localhost/poster
    username: "root"
    password: youngseo0@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true